version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: monitor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_backend
    environment:
      - DATABASE_URL=postgresql://root:123@db/monitor_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge

volumes:
  postgres_data:
